version: '2'
services:
  app:
    image: 'recipebook/app:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update       
    ports:
      - 8080:8080
  dbadmin:
    image: 'dpage/pgadmin4:6.10'
    container_name: dbadmin
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80      
    ports:
      - 8082:80
  db:
    image: 'postgres:14.3-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
